### ISSUE TITLE
QD-channel example crashes due to missing setter for the frequency attribute

### ISSUE THREAD

**Issue by pagmatt** [signetlabdei/qd-channel#4]
Currently the example `src/mmwave/examples/qd-channel-full-strck-example.cc` is not working; unfortunately this problem did not come up using ns-3 testing utilities as it looks like such test is skipped. Probably this is due to the fact that it is conditionally compiled only when this module is installed, and this is not picked up by the test script.
Anyway, the crash is triggered by the attribute class when the `mmwave-helper` tries to set the `Frequency` attribute for the qd-channel. This attribute actually does not have a setter method, since the frequency is read from the traces and set bypassing the attribute. With the latest ns-3 the lack of this setter triggers a crash. The possible solutions which come to mind are:
1. Use `SetAttributeFailSafe` in the helper. However, it is a workaround and it would no be my preferred choice.
2. Make an ad-hoc case in the helper, skipping the configuration of the `Frequency` parameter whenever the qd-channel is used.
3. Make a fake setter method for the frequency attribute which doesn't do anything, but which has the proper signature. This would be my preferred choice.
Please let me know what you think about this and which solution you prefer.

**Comment by mattia-lecci** [comment]
1. Is actually my preferred choice, by exclusion (see the others)
2. Making ad-hoc cases in the helper does not scale well and makes the helper aware of an extension that is not supposed to be there by default (or is the qd-channel included in the mmwave simulator by default?)
3. Making a fake setter method that does nothing is confusing for a user. The user might try to use it without reading the documentation or the logging outputs, making him thinks that the frequency was set while this was not the case. I think it would be very bad practice to do this

what do you think?

**Comment by pagmatt** [comment]
I don't like 1 because all other models have the frequency as an actually "settable" parameter. I think that using the FailSafe method can prevent us from spotting future bugs which involve such parameter. 

Since I think that the attribute is there only due to need for the Get method, the most elegant solution would be to have a "read-only" attribute, but it doesn't look that is possible at the moment...

**Comment by mattia-lecci** [comment]
makes sense. then what about option 3, logging a warn. log level warn should be active by default, right?

**Comment by pagmatt** [comment]
It would be a reasonable compromise! However, I believe that the new `Set` method would be also called by the helper when trying to set the `Frequency` attribute. Therefore, the log would be triggered both when the frequency is set by the helper (ok) and when users might try to manually set the frequency (what we wish to prevent).

**Comment by mattia-lecci** [comment]
Yep, and possibly at the creation of the QdChannel class as well, right?

We should write a clear warning stating the problem. something like `The Frequency attribute is being set automatically based on the read channel traces. The user should not set manually this attribute.`

**Comment by pagmatt** [comment]
That is fine for me. 
P.S. No log level apart from UNCOND is active by default.. I think that if we want to be absolutely sure that the method is not misused we could make the Set method indeed set an additional frequency value and then compare it to the one read by the parsing method (or initialize to min value and check that if different, it matches with the parsed frequency). However, it probably  would not be that elegant.. [This is my last remark, promised :D]

**Comment by mattia-lecci** [comment]
leaving an UNCOND log would be ugly, wouldn't it?

I would be ok if we would compare the new frequency with the one from the qd files, asserting whether it's the same or not.
It would be a bit unelegant maybe, but it's probably the safest way.

The alternative is documenting it and let the user decide what to do..

**Comment by pagmatt** [comment]
> leaving an UNCOND log would be ugly, wouldn't it?

Yes, I think this would be bad practice, especially because it would be always triggered when using the qd-channel..

> I would be ok if we would compare the new frequency with the one from the qd files, asserting whether it's the same or not.
> It would be a bit unelegant maybe, but it's probably the safest way.

All things considered I agree. Better to be safe than elegant :) I will create a PR with these changes soon
